name: PDAP
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - jupyter
  - seaborn
  - nltk
  - pip
  - pip:
    - wordcloud